{% set name = "blackcellmagic" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8d42fb462d0fd6ebdb1a9fec825f40493ceb84348d052daf14765689008a665

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - black
    - ipython
    - python

test:
  imports:
    - blackcellmagic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/csurfer/blackcellmagic
  summary: IPython wrapper to format cell using black.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
